apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ixl-frontend-automotive-commerce-template
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: ixl-frontend-automotive-commerce-deployment
    spec:
      selector:
        matchLabels:
          app: ixl-frontend-automotive-commerce
      replicas: 1
      template:
        metadata:
          labels:
            app: ixl-frontend-automotive-commerce
        spec:
          containers:
            - name: ixl-frontend-automotive-commerce
              image: ${IMAGE}
              imagePullPolicy: Always
              ports:
                - containerPort: 3000
              env:
                - name: GRAPHQL_ENDPOINT
                  value: ${GRAPHQL_ENDPOINT}
                - name: PRODUCT_PLACEHOLDER
                  value: '/static/images/placeholder.jpg'
                - name: IMAGE_EXTENSION
                  value: '.png'
                - name: THEME
                  value: 'packages/themes/automotive-theme/src/index.ts'
                - name: CDN_URL
                  value: 'https://res.cloudinary.com/di20gbxq3/automotive'

  - apiVersion: v1
    kind: Service
    metadata:
      name: ixl-frontend-automotive-commerce-service
    spec:
      selector:
        app: ixl-frontend-automotive-commerce
      ports:
        - protocol: 'TCP'
          port: 3200
          targetPort: 3000
      type: NodePort
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: ixl-frontend-automotive-commerce
    spec:
      to:
        kind: Service
        name: ixl-frontend-automotive-commerce-service
        weight: 100
      port:
        targetPort: 3000
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
parameters:
  - displayName: Image Location
    name: IMAGE
  - displayName: GraphQL Endpoint
    name: GRAPHQL_ENDPOINT
    value: 'http://boilerplate-ixl-adapter-commerce.apps.audi-commerce-cluster.redhat-engineroom.co.uk/graphql'
